
# Site settings
title: Hao Xue
name: Hao Xue
subtitle: MS candidate in Biostatistics at Harvard Chan
email: hao_xue@hsph.harvard.edu
description: >
  MS candidate in Biostatistics
baseurl: ""
url: "https://xvehao.github.io/"
github_username:  xvehao
disqus_baseurl: "https://xvehao.github.io/"
disqus_shortname: https-xvehao-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Hao Xue"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/xvehao
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://www.linkedin.com/in/hao-xue-178b38150/
    desc: Connect with me on LinkedIn
    share: true
